# xasset/debug/renderers/mesh_obj.py
"""OBJ exporter: MeshBuildOutput -> .obj + .mtl files."""
import os
from xasset.pipeline.stages.mesh_build import MeshBuildOutput

ROLE_MATERIALS = {
    "floor":      ("mtl_floor",      "0.76 0.70 0.60"),
    "ceiling":    ("mtl_ceiling",    "0.95 0.95 0.95"),
    "wall_inner": ("mtl_wall_inner", "0.85 0.82 0.78"),
    "wall_outer": ("mtl_wall_outer", "0.70 0.68 0.65"),
    "wall_top":   ("mtl_wall_top",   "0.80 0.78 0.75"),
}
DEFAULT_MATERIAL = ("mtl_default", "0.80 0.80 0.80")


def export_mesh_obj(output: MeshBuildOutput, obj_path: str) -> None:
    """Export MeshBuildOutput to .obj + .mtl files."""
    mtl_path = obj_path.replace(".obj", ".mtl")
    mtl_name = os.path.basename(mtl_path)

    lines_obj = ["# Generated by xasset debug exporter", f"mtllib {mtl_name}", ""]
    lines_mtl = ["# xasset debug materials", ""]

    written_mtls: set = set()
    for region in output.scene_mesh.regions:
        for submesh in _iter_submeshes(region):
            mat_name, rgb = ROLE_MATERIALS.get(submesh.role, DEFAULT_MATERIAL)
            if mat_name not in written_mtls:
                lines_mtl += [f"newmtl {mat_name}", f"Kd {rgb}",
                               "Ka 0.1 0.1 0.1", "Ks 0.0 0.0 0.0", ""]
                written_mtls.add(mat_name)

    vertex_offset = 1
    for region in output.scene_mesh.regions:
        lines_obj.append(f"# region {region.region_id}")
        for submesh in _iter_submeshes(region):
            mat_name, _ = ROLE_MATERIALS.get(submesh.role, DEFAULT_MATERIAL)
            lines_obj.append(f"g {region.region_id}_{submesh.role}")
            lines_obj.append(f"usemtl {mat_name}")
            for v in submesh.vertices:
                lines_obj.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
            for f in submesh.faces:
                i, j, k = f[0]+vertex_offset, f[1]+vertex_offset, f[2]+vertex_offset
                lines_obj.append(f"f {i} {j} {k}")
            vertex_offset += len(submesh.vertices)
            lines_obj.append("")

    with open(obj_path, "w") as fp:
        fp.write("\n".join(lines_obj))
    with open(mtl_path, "w") as fp:
        fp.write("\n".join(lines_mtl))


def _iter_submeshes(room):
    if room.floor:
        yield room.floor
    if room.ceiling:
        yield room.ceiling
    for wall in room.walls:
        for sm in wall.submeshes:
            yield sm
